"use client";

// next/image loader for hosts without an image optimizer (Cloudflare Workers).
// Local JPG/PNG files are served as the WebP variants pre-generated by
// scripts/build-image-variants.mjs; everything else (remote Scalev/Sanity
// images, SVG, GIF) is passed through untouched.

const BUCKETS = [384, 828, 1280]; // keep in sync with WIDTHS in the script
const RASTER = /\.(jpe?g|png)$/i;

export default function imageLoader({ src, width }: { src: string; width: number }) {
  if (!src.startsWith("/") || src.startsWith("//") || !RASTER.test(src)) return src;
  const bucket = BUCKETS.find((b) => width <= b) ?? BUCKETS[BUCKETS.length - 1];
  return `/_img${src.replace(RASTER, "")}.${bucket}.webp`;
}
